apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.10-focal
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
           secretKeyRef:
            name: mongodb-secret
            # secret config's metadata name
            key: mongo-root-username
            # secret config's data
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mongodb-secret
            # secret config's metadata name
            key: mongo-root-password
            # secret config's data


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  # random name
spec:
  selector:
    app: mongodb
    # Connect to Pod through label (metadata label app)
  ports:
  - protocol: TCP
    port: 27017
    # Service Port
    targetPort: 27017
    # Container Port of Deployment
